module.exports = {
    "name":"友奥蓝牙空调",
    "version":"1.0.1",
    "Serial":{
        "orderList":[
            {
                "name":"蓝牙配网",
                "order":"55 AA 03 04 00 00 03"
            },
        ],
        "serialInfo":{
            "rule":[
                {
                    "name":"Head",
                    "type":"Default",
                    "site":[0,1]
                },{
                    "name":"version",
                    "type":"Default",
                    "site":[2]
                },{
                    "name":"OCW",
                    "type":"Default",
                    "site":[3]
                },{
                    "name":"OCWLen",
                    "type":"Dec",
                    "site":[4,5]
                },{
                    "name":"Message",
                    "type":"Message",
                    "site":[6,"Len"]
                },{
                    "name":"Chcek",
                    "type":"Default",
                    "site":["end"]
                }
            ],
            "04":{
                "type":"上行消息",
                "analysis":"设备配网"
            },
            "06":{
                "type":"下行消息",
                "1":{
                    "rule":[
                        {
                            "name":"powerstate",
                            "Content":{"0":"关闭","1":"开启"}
                        }
                    ],
                    "analysis":"开关:${powerstate}"
                },
                "2":{
                    "rule":[
                        {
                            "name":"targetTemperature"
                        }
                    ],
                    "analysis":"设置温度为:${targetTemperature}"
                },
                "3":{
                    "rule":[
                        {
                            "name":"temperature"
                        }
                    ],
                    "analysis":"室内温度为:${temperature}度"
                },
                "4":{
                    "rule":[
                        {
                            "name":"mode",
                            "Content":{"0":"制冷","1":"送风","2":"除湿","3":"制热"}
                        }
                    ],
                    "analysis":"工作模式为:${mode}"
                },
                "5":{
                    "rule":[
                        {
                            "name":"windspeed",
                            "Content":{"0":"低档","1":"中档","2":"高档"}
                        }
                    ],
                    "analysis":"风速为:${windspeed}"
                },
                "19":{
                    "rule":[
                        {
                            "name":"unitType",
                            "Content":{"0":"公制","1":"英制"}
                        }
                    ],
                    "analysis":"温标为:${unitType}"
                },
                "104":{
                    "rule":[
                        {
                            "name":"angleAutoUDOnOff",
                            "Content":{"0":"关","1":"开"}
                        }
                    ],
                    "analysis":"摆风:${angleAutoUDOnOff}"
                }
            },
            "07":{
                "type":"上行消息",
                "1":{
                    "rule":[
                        {
                            "name":"powerstate",
                            "Content":{"0":"关闭","1":"开启"}
                        }
                    ],
                    "analysis":"开关:${powerstate}"
                },
                "2":{
                    "rule":[
                        {
                            "name":"targetTemperature"
                        }
                    ],
                    "analysis":"设置温度为:${targetTemperature}"
                },
                "3":{
                    "rule":[
                        {
                            "name":"temperature"
                        }
                    ],
                    "analysis":"室内温度为:${temperature}度"
                },
                "4":{
                    "rule":[
                        {
                            "name":"mode",
                            "Content":{"0":"制冷","1":"送风","2":"除湿","3":"制热"}
                        }
                    ],
                    "analysis":"工作模式为:${mode}"
                },
                "5":{
                    "rule":[
                        {
                            "name":"windspeed",
                            "Content":{"0":"低档","1":"中档","2":"高档"}
                        }
                    ],
                    "analysis":"风速为:${windspeed}"
                },
                "19":{
                    "rule":[
                        {
                            "name":"unitType",
                            "Content":{"0":"公制","1":"英制"}
                        }
                    ],
                    "analysis":"温标为:${unitType}"
                },
                "104":{
                    "rule":[
                        {
                            "name":"angleAutoUDOnOff",
                            "Content":{"0":"关","1":"开"}
                        }
                    ],
                    "analysis":"摆风:${angleAutoUDOnOff}"
                }
            }
        },
        "functionList":{
            "checkbit": function(code) {
                let res=code.split(' ');
                code=res.slice(0,res.length-1);
                let sum=0;
                for (let i in code) {
                    sum=sum+parseInt(code[i],16);
                };
                res.splice(res.length-1,1,(Array(2).join(0) + Number(sum%256).toString(16)).slice(-2));
                res = res.join(' ').toUpperCase();
                return res;
            }
        }
    },
}